title: Wheel of Time
name: wheel-of-time
email: benthicmaw+lackey@gmail.com
description:
baseurl: "/lackey"
url: "https://lackey-plugins.github.io/wheel-of-time"
github_username:  lackey-plugins

exclude: [plugin, Makefile]
keep_files: [sets, decks, _site]