title: Wheel of Time
email: benthicmaw+lackey@gmail.com
description:
baseurl: /api
url: https://lackey-plugins.github.io/wheel-of-time
github_username:  lackey-plugins

data_dir: ../data

collections:

  sets:
    output: true
    sources:
      - sets.tsv
    related:
      - from_field: id
        to_field: set
        collection: cards
    id_key: id
    image_key: id
    layouts: [jsonapi]
    index: true
    image_base: https://lackey-plugins.github.io/wheel-of-time/images

  cards:
    output: true
    sources:
      - cards/premier.tsv
      - cards/dark_prophecies.tsv
      - cards/children_of_the_dragon.tsv
      - cards/cycles.tsv
      - cards/promo.tsv
    related:
      - from_field: set
        to_field: id
        collection: sets
    id_key: id
    image_key: id
    layouts: [jsonapi]
    index: true
    image_base: https://lackey-plugins.github.io/wheel-of-time/images

  decks:
    output: true
    sources:
      - decks.tsv
    related:
      - jsonlogic_array:
          column: main
        extra:
          meta:
            zone: main
            count: quantity
        from_field: id
        to_field: id
        collection: cards
    id_key: id
    image_key: id
    layouts: [jsonapi]
    index: true
    image_base: https://lackey-plugins.github.io/wheel-of-time/images

exclude: [README.MD", "data", "documents", "images", "_lackey"]
include: ["_index"]
