wget -O promo/battle_fury.jpg http://wotccg.mahasamatman.com/Promo/Gallery/003.JPG
wget -O promo/filled_with_power.jpg http://wotccg.mahasamatman.com/Promo/Gallery/002.JPG
wget -O promo/friend_of_the_dark.jpg http://wotccg.mahasamatman.com/Promo/Gallery/010.JPG
wget -O promo/moment_of_transition.jpg http://wotccg.mahasamatman.com/Promo/Gallery/009.JPG
wget -O promo/night_raid.jpg http://wotccg.mahasamatman.com/Promo/Gallery/001.JPG
wget -O promo/pitched_battle.jpg http://wotccg.mahasamatman.com/Promo/Gallery/008.JPG
wget -O promo/power_play.jpg http://wotccg.mahasamatman.com/Promo/Gallery/007.JPG
wget -O promo/things_yet_to_come.jpg http://wotccg.mahasamatman.com/Promo/Gallery/006.JPG
wget -O promo/uncontrolled_rage.jpg http://wotccg.mahasamatman.com/Promo/Gallery/005.JPG
wget -O promo/unravel_the_pattern.jpg http://wotccg.mahasamatman.com/Promo/Gallery/004.JPG